language: php
php:
  - 5.6
  - 5.5
  - hhvm

before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: vendor/bin/phpunit

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

notifications:
  on_success: never
  on_failure: never
